name: Run Python Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run tests with unittest
        run: |
          python -m unittest tests/test_zad1.py
          python -m unittest tests/test_zad2.py
          python -m unittest tests/test_zad3.py
© 2021 GitHub, Inc.
Terms
Privacy
Security
